### ISSUE TITLE
finish mp5k overhaul

### ISSUE THREAD

**Issue by GlitchyBoah** [Tuxxego/IVEngine-2#22]
todo: finish mp5k overhaul

**Comment by Tuxxego** [comment]
do it yourself lmao

**Comment by Tuxxego** [comment]
stop being lazy

**Comment by breakdowngamesYT** [comment]
thats what she said

**Comment by ledmic** [comment]
what? where is the punchline??

**Comment by Tuxxego** [comment]
what? lmao

**Comment by Tuxxego** [comment]
hey breakdown, message me on discord btw, i can get the code for your mod if you need it still. Tuxxego#4017

**Comment by ImmortalGlitchy** [comment]
i literally just closed this

**Comment by ImmortalGlitchy** [comment]
``

**Comment by breakdowngamesYT** [comment]
ok

**Comment by breakdowngamesYT** [comment]
sorry i was on vacation
